name: Practice GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Linting code"
  main-jobs:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - run: echo "🚀 Running workflow for MAIN branch"
      - run: node hello.js
 
  
   
